org: arturceschin
service: async-processing

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  environment:
    LIVES_TABLE: !Ref LivesTable
    LIVES_IMAGE_BUCKET: !Ref LivesImagesBucket
    IMAGE_PROCESSING_QUEUE_URL: !Ref ImageProcessingQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem

          #We need to pass the ARN -> Amazon Resource Name
          # And we don't need to copy and paste the arn from aws and paste it here
          # For this we will use the !GetAtt which is to get the attribute and for that we need
          # the logical name LivesTable. and inside there we have the Arn
          Resource: !GetAtt LivesTable.Arn
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Join ["/", [!GetAtt LivesImagesBucket.Arn, "*"]]
        - Effect: Allow
          Action: sqs:SendMessage
          Resource: !GetAtt ImageProcessingQueue.Arn

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
      - sharp
    external:
      - sharp

layers:
  Sharp:
    name: sharp-layer
    description: sharp package and its binaries
    path: layers/sharp
    retain: false
    compatibleArchitectures:
      - arm64
    compatibleRuntimes:
      - nodejs20.x

functions:
  createLive:
    handler: src/functions/http/createLive.handler
    events:
      - httpApi:
          path: /lives
          method: POST

  processImage:
    handler: src/functions/queues/processImage.handler
    timeout: 20
    layers:
      - !Ref SharpLambdaLayer
    events:
      - sqs:
          arn: !GetAtt ImageProcessingQueue.Arn
          batchSize: 10

  newS3ObjectTrigger:
    handler: src/functions/triggers/newS3ObjectTrigger.handler
    events:
      - s3:
          bucket: !Ref LivesImagesBucket
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
          rules:
            - prefix: uploads/

resources:
  Resources:
    # This is not the table name but the resource name
    LivesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Now this is the table name in dynamo
        TableName: LivesTable
        # Here is the Serverless pay type
        BillingMode: PAY_PER_REQUEST
        # We define the keys here
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S # means it is an string
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    LivesImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: youtube-async-processing-images
    ImageProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ImageProcessingQueue
        VisibilityTimeout: 20
        # wait 20 seconds before saing the queue is empty
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          # How many times we have already tried processing this?
          maxReceiveCount: 2
          deadLetterTargetArn: !GetAtt ImageProcessingDLQ.Arn
    ImageProcessingDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ImageProcessingDLQ
        MessageRetentionPeriod: 1209600 #14 days
